### ISSUE TITLE
Fails to create a valid signature for a PBO with / for directory separator

### ISSUE THREAD

**Issue by zharf** [BrettMayson/bisign#1]
**bisign version**: git d33fd06 (also 0.2)
Apparently Arma 3 is capable of using / as directory separator in filenames in a pbo and DSSignFile generates a valid signature for them. Signatures created by bisign will end up as invalid though.
Unpacking one such PBO and repacking it (on windows) without any modifications changed the directory separators into \ instead and DSSignFile and bisign then generated identical signatures.

Replacing / with \ in [mod.rs line 77](https://github.com/BrettMayson/bisign/blob/master/src/types/mod.rs#L77) also ended up with the correct result. I'm just not sure if you want to fix this in here or in pbo-rs instead.

**Example mod**: [GRAD Civs 5.0.3](https://github.com/gruppe-adler/grad_civs/releases/download/5.0.3/@grad_civs-5.0.3.zip) (they fixed this in 6.0.0 by using HEMTT on windows instead of linux)

I believe this is also the root cause for https://github.com/BrettMayson/HEMTT/issues/278

**Comment by BrettMayson** [comment]
Should be fixed by a82ebe32ede9833f298887072d73f7472a781006, bisign does need some tests added to prevent regression though

**Comment by overfl0** [comment]
Hello, is there any chance for the code mentioned in this issue to be released?
The last release available on github, in binary form is 0.2

**Comment by BrettMayson** [comment]
Fixed in v0.4.0
