### ISSUE TITLE
Panics on creating signature

### ISSUE THREAD

**Issue by Perondas** [BrettMayson/bisign#3]
Bisign panics  with the following message when trying to sign "swlw_main.pbo" from [this](https://steamcommunity.com/sharedfiles/filedetails/?id=2162749089)

```text
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [101, 102, 102, 101, 99, 116, 115, 92, 100, 97, 116, 97, 92, 218, 106, 32, 109, 97, 112, 112, 97, 92, 77, 117, 122, 122, 108, 101, 70, 108, 97, 115, 10                                                                       4, 95, 98, 108, 117, 101, 95, 49, 46, 112, 97, 97], error: Utf8Error { valid_up_to: 13, error_len: Some(1) } }', /home/perondas/.cargo/git/checkouts/hemtt-0af4dec33e335ee6/76bb25f/hemtt-io/src/lib.rs:20:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by BrettMayson** [comment]
Bisign is being deprecated in favour of HEMTT utils coming in the 1.10 release. However, there will not be support initially for creating signatures. Creating signatures on their own is considered too dangerous by HEMTT, and is not supported.

**Comment by Perondas** [comment]
Sad to hear that. 
What do you mean with "dangerous"?

**Comment by BrettMayson** [comment]
I meant to put "Creating private keys". HEMTT intentionally does not allow creating, storing, and reusing private keys.

It could unknowingly be stolen and used to load tampered files on a server

**Comment by Perondas** [comment]
Understandable. Guess ill just have to fix this (and other) issues with signing myself, since I really do need an alternative to the A3 tools.

**Comment by BrettMayson** [comment]
You can create a feature request on HEMTT, and see if anyone else really needs this. If there is enough interest I would consider creating options for this.

**Comment by Perondas** [comment]
Cool. I have already figured out how to make the signing work for "most" files. 
All that is left are some Edge Cases where I am left guessing as to what to do.
I may just open an Issue and a PR.
